# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainLogin(object):
    def setupUi(self, MainLogin):
        MainLogin.setObjectName("MainLogin")
        MainLogin.resize(800, 529)
        MainLogin.setStyleSheet("background-color: rgb(234, 255, 231);")
        self.centralwidget = QtWidgets.QWidget(parent=MainLogin)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 50, 301, 441))
        self.groupBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.username = QtWidgets.QLineEdit(parent=self.groupBox)
        self.username.setGeometry(QtCore.QRect(130, 60, 141, 21))
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(parent=self.groupBox)
        self.password.setGeometry(QtCore.QRect(130, 110, 141, 21))
        self.password.setObjectName("password")
        self.btn_login = QtWidgets.QPushButton(parent=self.groupBox)
        self.btn_login.setGeometry(QtCore.QRect(100, 180, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_login.setFont(font)
        self.btn_login.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"color: rgb(255, 255, 255);")
        self.btn_login.setObjectName("btn_login")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(350, 50, 451, 441))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("image/tong-quan-chung-nhan-2.jpg"))
        self.label.setObjectName("label")
        MainLogin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainLogin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainLogin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainLogin)
        self.statusbar.setObjectName("statusbar")
        MainLogin.setStatusBar(self.statusbar)

        self.retranslateUi(MainLogin)
        QtCore.QMetaObject.connectSlotsByName(MainLogin)

    def retranslateUi(self, MainLogin):
        _translate = QtCore.QCoreApplication.translate
        MainLogin.setWindowTitle(_translate("MainLogin", "MainWindow"))
        self.label_2.setText(_translate("MainLogin", "Username"))
        self.label_3.setText(_translate("MainLogin", "Password"))
        self.btn_login.setText(_translate("MainLogin", "Đăng nhập"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainLogin = QtWidgets.QMainWindow()
    ui = Ui_MainLogin()
    ui.setupUi(MainLogin)
    MainLogin.show()
    sys.exit(app.exec())
